parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $wampURL: '%env(resolve:WAMP_URL)%'
            $authid: '%env(resolve:USER_NAME)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\WampServer\Security\ClientAuthenticator\UserClientAuthenticator:
        tags:
            - { name: app.client.client_authenticator }